# Generated by Django 4.1.5 on 2023-03-26 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseCode', models.CharField(max_length=255)),
                ('courseName', models.CharField(max_length=255)),
                ('teachingSchemeTH', models.CharField(max_length=255)),
                ('teachingSchemeP', models.CharField(max_length=255)),
                ('teachingSchemeTUT', models.CharField(max_length=255)),
                ('TotalHours', models.CharField(max_length=255)),
                ('creditAssignedTH', models.CharField(max_length=255)),
                ('creditAssignedP', models.CharField(max_length=255)),
                ('creditAssignedTUT', models.CharField(max_length=255)),
                ('totalCredits', models.CharField(max_length=255)),
                ('courseCategories', models.CharField(max_length=255)),
            ],
        ),
    ]
