# Generated by Django 4.1.5 on 2023-03-27 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_creditscheme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditscheme',
            name='TotalHours',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='creditscheme',
            name='creditAssignedP',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='creditscheme',
            name='creditAssignedTH',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='creditscheme',
            name='creditAssignedTUT',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='creditscheme',
            name='teachingSchemeP',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='creditscheme',
            name='teachingSchemeTH',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='creditscheme',
            name='teachingSchemeTUT',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='creditscheme',
            name='totalCredits',
            field=models.IntegerField(),
        ),
    ]
