# Generated by Django 4.1.5 on 2023-03-28 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_creditscheme_sem'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditscheme',
            name='programme',
            field=models.CharField(max_length=255),
            preserve_default=False,
        ),
    ]
