# Generated by Django 4.1.5 on 2023-03-28 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_creditscheme_programme'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamSchm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseCodeEx', models.CharField(max_length=255)),
                ('courseNameEx', models.CharField(max_length=255)),
                ('caISE', models.IntegerField()),
                ('caIA', models.IntegerField()),
                ('caTotal', models.IntegerField()),
                ('ese', models.IntegerField()),
                ('tw', models.IntegerField()),
                ('oral', models.IntegerField()),
                ('oralAndPrac', models.IntegerField()),
                ('totalEx', models.IntegerField()),
                ('branch', models.CharField(max_length=255)),
                ('sem', models.CharField(max_length=255)),
                ('programme', models.CharField(max_length=255)),
            ],
        ),
    ]
