# Generated by Django 4.1.5 on 2023-03-28 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_examschm'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examschm',
            old_name='branch',
            new_name='brancH',
        ),
        migrations.RenameField(
            model_name='examschm',
            old_name='programme',
            new_name='programmE',
        ),
        migrations.RenameField(
            model_name='examschm',
            old_name='sem',
            new_name='seM',
        ),
    ]
