# Generated by Django 4.1.5 on 2023-03-28 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_rename_branch_examschm_branch_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examschm',
            old_name='brancH',
            new_name='branch',
        ),
        migrations.RenameField(
            model_name='examschm',
            old_name='programmE',
            new_name='programme',
        ),
        migrations.RenameField(
            model_name='examschm',
            old_name='seM',
            new_name='sem',
        ),
    ]
