# Generated by Django 4.1.7 on 2023-03-30 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_examschm_calabtut_examschm_coursecategoriesex'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignfaculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseCodeEx', models.CharField(max_length=255)),
                ('courseNameEx', models.CharField(max_length=255)),
                ('faculty1', models.CharField(max_length=255)),
                ('faculty2', models.CharField(max_length=255)),
                ('faculty3', models.CharField(max_length=255)),
                ('reviewer', models.CharField(max_length=255)),
                ('branch', models.CharField(max_length=255)),
                ('sem', models.CharField(max_length=255)),
                ('programme', models.CharField(max_length=255)),
            ],
        ),
    ]
