# Generated by Django 4.1.5 on 2023-03-31 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_remove_assignfaculty_id_remove_creditscheme_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignfaculty',
            name='id',
            field=models.AutoField(default=15, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='creditscheme',
            name='id',
            field=models.AutoField(default=13, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='examschm',
            name='id',
            field=models.AutoField(default=14, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assignfaculty',
            name='courseCodeEx',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='creditscheme',
            name='courseCode',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='examschm',
            name='courseCodeEx',
            field=models.CharField(max_length=255),
        ),
    ]
