# Generated by Django 4.1.7 on 2023-04-01 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_assignfaculty_id_creditscheme_id_examschm_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='role',
            field=models.CharField(choices=[('HOD', 'Hod'), ('CREATOR', 'Creator'), ('TEACHER', 'Teacher')], max_length=100),
        ),
    ]
