# Generated by Django 4.1.7 on 2023-04-01 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_alter_teacher_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='role',
            field=models.CharField(choices=[('HOD', 'Hod'), ('CREATOR', 'Creator'), ('TEACHER', 'Teacher'), ('REVIEWER', 'REVIEWER')], max_length=100),
        ),
    ]
