# Generated by Django 4.1.7 on 2023-04-13 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_alter_teacher_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='examschm',
            name='credit_scheme',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='account.creditscheme'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='examschm',
            name='courseCodeEx',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='examschm',
            name='courseNameEx',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
